const buttonStyle = {
    backgroundColor: "#075985",
    paddingVertical: 16,
    paddingHorizontal: 42,
    backgroundColor: "#075985",
    borderRadius: 8,
    width: "100%",
    height: 50,
  },
  topViewStyle = { height: 450, backgroundColor: "#0A2540", color: "white" },
  textWelcome = {
    position: "absolute",
    left: "50%",
    top: "7.78%",
    transform: [{ translateX: -58.5 }],
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.04,
    color: "#FFFFFF",
    paddingBottom: 100,
  },
  longText = {
    position: "absolute",
    left: "5.6%",
    right: "5.6%",
    top: "65.45%",
    bottom: "11.57%",
    fontStyle: "normal",
    fontWeight: "700",
    fontSize: 32,
    lineHeight: 44,
    letterSpacing: -0.04,
    color: "#FFFFFF",
  },
  bottomView = {
    padding: "5%",
    paddingTop: "10%",
    gap: 20,
    backgroundColor: "#F9F9F9",
  },
  textSignUP = {
    color: "#075985",
  },
  textDetail = {
    position: "absolute",
    left: "5.6%",
    right: "49.07%",
    top: "90.08%",
    bottom: "5.58%",
    fontStyle: "normal",
    fontWeight: "500",
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: -0.04,
    color: "#FFFFFF",
  };

export {
  textDetail,
  buttonStyle,
  topViewStyle,
  textWelcome,
  longText,
  bottomView,
  textSignUP,
};
